### ISSUE TITLE
Link to the two sub packages

### ISSUE THREAD

**Issue by RemyLau** [AnacletoLAB/grape#20]
Hi, first of all, thanks for making such an amazing graph embedding resource!

I'm wondering whether you can add some descriptions in the README clarifying that this repo is a thin wrapper of the two core packages [embiggen](https://github.com/monarch-initiative/embiggen) and [ensmallen](https://github.com/AnacletoLAB/ensmallen) and add links accordingly. I was a bit confused for a few minutes trying to find the source code and only came to realize it wraps the two libraries after looking at `__init__.py`.

**Comment by LucaCappelletti94** [comment]
In Embiggen and Ensmallen README, we say, "these are a submodule of GRAPE. Refer to the GRAPE library for documentation etc...", but I did not think to write this the other way around, which we can surely add to avoid confusion.

This is mainly done because of software engineering needs since the tooling necessary to build Ensmallen is significantly different and much more complex than what is needed for Embiggen.

**Comment by RemyLau** [comment]
> In Embiggen and Ensmallen README, we say, "these are a submodule of GRAPE. Refer to the GRAPE library for documentation etc...", but I did not think to write this the other way around, which we can surely add to avoid confusion.
> 
> This is mainly done because of software engineering needs since the tooling necessary to build Ensmallen is significantly different and much more complex than what is needed for Embiggen.

I see! Yeah, I think adding a similar note to the Grape README could be helpful for users since the API they know of / use would be Grape.

**Comment by LucaCappelletti94** [comment]
I have added a short line on this at the beginning of the README. Does it fit the bill, in your opinion?

**Comment by RemyLau** [comment]
Yes it looks great!
