### ISSUE TITLE
Method not found in api documentation: Graph.from_pd

### ISSUE THREAD

**Issue by jonsenhb** [AnacletoLAB/grape#54]
Hi， After I installed grape 0.2.2 version, I can use the Graph.from_pd method by referring to the example, but I cannot find a detailed description of this method in the api document. It would be really great if the documentation could be updated.

Thanks and best wishes！

**Comment by LucaCappelletti94** [comment]
Hi! The reference documentation we suggest you use and that we use is simply the help function from Python, as in `help(Graph.from_pd)`.

Creating a documentation website is not feasible for the foreseeable future because we provide too many methods (e.g. the over 80k graphs from the retrieval) and that breaks most of the tools for generating documentation. At this time, we do not have the budget to develop our own website.

**Comment by jonsenhb** [comment]
Thank you very much, I understand. This is a great project, best wishes
